# Generated by Django 4.1 on 2024-01-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
